%import common.CNAME

%import common.WS
%ignore WS

WILDCARD: "*"

node: CNAME
port: node "." (CNAME | WILDCARD)
input: port
output: port
connection: output "->" input

command: ("link" | "connect" | "attach") connection                       -> link
       | ("unlink" | "disconnect" | "detach") (node | port | connection)  -> unlink
       | ("delete" | "remove") node                                       -> delete

?expression: [node | port | connection | command]

?start: expression
