%import common.CNAME

%import common.WS
%ignore WS

node: CNAME
wildcard: "*"
port: node "." (CNAME | wildcard)
connection: port "->" port

command: ["link" | "connect" | "attach"] connection                       -> link
       | ("unlink" | "disconnect" | "detach") (node | port | connection)  -> unlink
       | ("delete" | "remove") node                                         -> delete

?start: command
